package kotlin.reflect.jvm.internal.impl.util;

import java.util.Set;
import kotlin.collections.SetsKt;
import kotlin.jvm.internal.Intrinsics;
import kotlin.reflect.jvm.internal.impl.name.Name;
import kotlin.text.Regex;

/* compiled from: OperatorNameConventions.kt */
public final class OperatorNameConventions {
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final Regex COMPONENT_REGEX = new Regex("component\\d+");
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name MOD;
    public static final Name MOD_ASSIGN;
    public static final Name NEXT;
    public static final Name NOT;

    /* renamed from: OR */
    public static final Name f369OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;

    private OperatorNameConventions() {
    }

    static {
        Name identifier = Name.identifier("getValue");
        Intrinsics.checkNotNullExpressionValue(identifier, "identifier(\"getValue\")");
        GET_VALUE = identifier;
        Name identifier2 = Name.identifier("setValue");
        Intrinsics.checkNotNullExpressionValue(identifier2, "identifier(\"setValue\")");
        SET_VALUE = identifier2;
        Name identifier3 = Name.identifier("provideDelegate");
        Intrinsics.checkNotNullExpressionValue(identifier3, "identifier(\"provideDelegate\")");
        PROVIDE_DELEGATE = identifier3;
        Name identifier4 = Name.identifier("equals");
        Intrinsics.checkNotNullExpressionValue(identifier4, "identifier(\"equals\")");
        EQUALS = identifier4;
        Name identifier5 = Name.identifier("compareTo");
        Intrinsics.checkNotNullExpressionValue(identifier5, "identifier(\"compareTo\")");
        COMPARE_TO = identifier5;
        Name identifier6 = Name.identifier("contains");
        Intrinsics.checkNotNullExpressionValue(identifier6, "identifier(\"contains\")");
        CONTAINS = identifier6;
        Name identifier7 = Name.identifier("invoke");
        Intrinsics.checkNotNullExpressionValue(identifier7, "identifier(\"invoke\")");
        INVOKE = identifier7;
        Name identifier8 = Name.identifier("iterator");
        Intrinsics.checkNotNullExpressionValue(identifier8, "identifier(\"iterator\")");
        ITERATOR = identifier8;
        Name identifier9 = Name.identifier("get");
        Intrinsics.checkNotNullExpressionValue(identifier9, "identifier(\"get\")");
        GET = identifier9;
        Name identifier10 = Name.identifier("set");
        Intrinsics.checkNotNullExpressionValue(identifier10, "identifier(\"set\")");
        SET = identifier10;
        Name identifier11 = Name.identifier("next");
        Intrinsics.checkNotNullExpressionValue(identifier11, "identifier(\"next\")");
        NEXT = identifier11;
        Name identifier12 = Name.identifier("hasNext");
        Intrinsics.checkNotNullExpressionValue(identifier12, "identifier(\"hasNext\")");
        HAS_NEXT = identifier12;
        Name identifier13 = Name.identifier("toString");
        Intrinsics.checkNotNullExpressionValue(identifier13, "identifier(\"toString\")");
        TO_STRING = identifier13;
        Name identifier14 = Name.identifier("and");
        Intrinsics.checkNotNullExpressionValue(identifier14, "identifier(\"and\")");
        AND = identifier14;
        Name identifier15 = Name.identifier("or");
        Intrinsics.checkNotNullExpressionValue(identifier15, "identifier(\"or\")");
        f369OR = identifier15;
        Name identifier16 = Name.identifier("inc");
        Intrinsics.checkNotNullExpressionValue(identifier16, "identifier(\"inc\")");
        INC = identifier16;
        Name identifier17 = Name.identifier("dec");
        Intrinsics.checkNotNullExpressionValue(identifier17, "identifier(\"dec\")");
        DEC = identifier17;
        Name identifier18 = Name.identifier("plus");
        Intrinsics.checkNotNullExpressionValue(identifier18, "identifier(\"plus\")");
        PLUS = identifier18;
        Name identifier19 = Name.identifier("minus");
        Intrinsics.checkNotNullExpressionValue(identifier19, "identifier(\"minus\")");
        MINUS = identifier19;
        Name identifier20 = Name.identifier("not");
        Intrinsics.checkNotNullExpressionValue(identifier20, "identifier(\"not\")");
        NOT = identifier20;
        Name identifier21 = Name.identifier("unaryMinus");
        Intrinsics.checkNotNullExpressionValue(identifier21, "identifier(\"unaryMinus\")");
        UNARY_MINUS = identifier21;
        Name identifier22 = Name.identifier("unaryPlus");
        Intrinsics.checkNotNullExpressionValue(identifier22, "identifier(\"unaryPlus\")");
        UNARY_PLUS = identifier22;
        Name identifier23 = Name.identifier("times");
        Intrinsics.checkNotNullExpressionValue(identifier23, "identifier(\"times\")");
        TIMES = identifier23;
        Name identifier24 = Name.identifier(TtmlNode.TAG_DIV);
        Intrinsics.checkNotNullExpressionValue(identifier24, "identifier(\"div\")");
        DIV = identifier24;
        Name identifier25 = Name.identifier("mod");
        Intrinsics.checkNotNullExpressionValue(identifier25, "identifier(\"mod\")");
        MOD = identifier25;
        Name identifier26 = Name.identifier("rem");
        Intrinsics.checkNotNullExpressionValue(identifier26, "identifier(\"rem\")");
        REM = identifier26;
        Name identifier27 = Name.identifier("rangeTo");
        Intrinsics.checkNotNullExpressionValue(identifier27, "identifier(\"rangeTo\")");
        RANGE_TO = identifier27;
        Name identifier28 = Name.identifier("timesAssign");
        Name name = identifier3;
        Intrinsics.checkNotNullExpressionValue(identifier28, "identifier(\"timesAssign\")");
        TIMES_ASSIGN = identifier28;
        Name identifier29 = Name.identifier("divAssign");
        Name name2 = identifier2;
        Intrinsics.checkNotNullExpressionValue(identifier29, "identifier(\"divAssign\")");
        DIV_ASSIGN = identifier29;
        Name identifier30 = Name.identifier("modAssign");
        Name name3 = identifier;
        Intrinsics.checkNotNullExpressionValue(identifier30, "identifier(\"modAssign\")");
        MOD_ASSIGN = identifier30;
        Name identifier31 = Name.identifier("remAssign");
        Name name4 = identifier30;
        Intrinsics.checkNotNullExpressionValue(identifier31, "identifier(\"remAssign\")");
        REM_ASSIGN = identifier31;
        Name identifier32 = Name.identifier("plusAssign");
        Name name5 = identifier31;
        Intrinsics.checkNotNullExpressionValue(identifier32, "identifier(\"plusAssign\")");
        PLUS_ASSIGN = identifier32;
        Name identifier33 = Name.identifier("minusAssign");
        Intrinsics.checkNotNullExpressionValue(identifier33, "identifier(\"minusAssign\")");
        MINUS_ASSIGN = identifier33;
        Name name6 = identifier33;
        UNARY_OPERATION_NAMES = SetsKt.setOf(identifier16, identifier17, identifier22, identifier21, identifier20);
        SIMPLE_UNARY_OPERATION_NAMES = SetsKt.setOf(identifier22, identifier21, identifier20);
        BINARY_OPERATION_NAMES = SetsKt.setOf(identifier23, identifier18, identifier19, identifier24, identifier25, identifier26, identifier27);
        ASSIGNMENT_OPERATIONS = SetsKt.setOf(identifier28, identifier29, name4, name5, identifier32, name6);
        DELEGATED_PROPERTY_OPERATORS = SetsKt.setOf(name3, name2, name);
    }
}
